#!/bin/bash

echo "Criar diretórios..."
mkdir /publico /adm /ven /sec

echo "Criar grupos de usúarios..."
groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

echo "Criar grupos de usúarios para alocar no servidor..."
useradd carlos -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_ADM
useradd monica -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_ADM
useradd debora -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_ADM
useradd sidney -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_VEN
useradd carla -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_VEN
useradd joelma -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_VEN
useradd beatriz -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_SEC
useradd bruno -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_SEC
useradd dennilsom -m -s /bin/bash -p $(openssl passwd Senha123) -G GRP_SEC

echo "Agora setando permissões..."
chown root:GRP_ADM /adm
chown root:GRP_SEC /sec
chown root:GRP_VEN /ven
chown 770 /ven
chown 770 /adm
chown 770 /sec
chown 777 /publico

echo "Nothing more to do my friend..."
